
CREATE TABLE [TEST_DATABASE].[dbo].[Survey] (
    id INT PRIMARY KEY IDENTITY(1,1),
    Title VARCHAR(256) NOT NULL,
    StartAt DATETIME,
    EndAt DATETIME,
    Description VARCHAR(MAX) NOT NULL,
    CreatedBy VARCHAR(256) NOT NULL
);


CREATE TABLE [TEST_DATABASE].[dbo].[Question] (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    SurveyId INT NOT NULL,
    Text VARCHAR(256) NOT NULL,
    Type VARCHAR(256) NOT NULL
);


CREATE TABLE [TEST_DATABASE].[dbo].[MCAnswer] (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    questionId INT NOT NULL,
    Text VARCHAR(256) NOT NULL,
);
